baseurl = "/"
languageCode = "en-us"
title = "circuit-switching"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "[Github](https://github.com/orgs/TritonNetworking) | [CSE Dept](https://www.cs.ucsd.edu) | [JSOE](https://jacobsschool.ucsd.edu/) | [UC San Diego](https://www.ucsd.edu)"
    custom_css = ["css/theme-override.css"]
